# Generated by Django 5.2.16 on 2026-07-28 17:06

import django.core.validators
import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, unique=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Digite um telefone válido.', regex='^\\+?[\\d\\s\\-\\(\\)]+$')])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('emergency_contact_name', models.CharField(max_length=200)),
                ('emergency_contact_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Digite um telefone válido.', regex='^\\+?[\\d\\s\\-\\(\\)]+$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
