# Generated by Django 5.2.16 on 2026-07-31 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('body_fat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('muscle_mass', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('abdomen', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hip', models.DecimalField(decimal_places=2, max_digits=5)),
                ('right_arm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('left_arm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('right_thigh', models.DecimalField(decimal_places=2, max_digits=5)),
                ('left_thigh', models.DecimalField(decimal_places=2, max_digits=5)),
                ('right_calf', models.DecimalField(decimal_places=2, max_digits=5)),
                ('left_calf', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observation', models.TextField(blank=True, max_length=200, null=True)),
                ('assessment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='students.student')),
            ],
        ),
    ]
