# Generated by Django 5.2.16 on 2026-08-01 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='creat_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
