# Generated by Django 5.2.16 on 2026-07-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('muscle_group', models.TextField(choices=[('CHEST', 'Peitoral'), ('BACK', 'Costas'), ('SHOULDERS', 'Ombros'), ('BICEPS', 'Bíceps'), ('TRICEPS', 'Tríceps'), ('LEGS', 'Pernas'), ('GLUTES', 'Glúteos'), ('ABS', 'Abdômen'), ('CARDIO', 'Cardio')], max_length=20)),
                ('equipment', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercise_images/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
