# Generated by Django 5.2.16 on 2026-08-01 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='start_date',
            new_name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='end_date',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativa'), ('SUSPENDED', 'Suspensa'), ('CANCELLED', 'Cancelada'), ('FINISHED', 'Finalizada')], default='ACTIVE', max_length=15),
        ),
    ]
